export class AnnouncementParams {
    priceMin: string;
    priceMax: string;
    propertyType: string;
    shower: boolean;
    oven: boolean;
    bath: boolean;
    microwave: boolean;
    elevator: boolean;
    petsAllowed: boolean;
    nearPark: boolean;
    fenced: boolean;
    nearTram: boolean;
    nearBus: boolean;
    wifi: boolean;
    ethernetOutlets: boolean;
    internet: boolean;
    internetSpeed: number;
    tv: boolean;
    dishwasher: boolean;
    clothesDryer: boolean;
    nearShoppingMall: boolean;
    nearBakery: boolean;
    nearFoodMarket: boolean;
    nearSupermarket: boolean;
    country: string;
    city: string;
    district: string;
    livingSpace: number;
    title: string;
    // flat
    floor: number;
    bedrooms: number;
    bathrooms: number;
    flatParking: number;
    balcony: number;
    // house
    floors: number;
    basement: boolean;
    lotSize: number;
    parking: boolean;
    //room
    bedsInRoom: number;
    numberOfFlatmates: number;
}