insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(100,'2021-11-15','poznan','polska','PLN','wilda','12/3',10,'61-78',999,'POKOJ','2021-11-18','wlkp','gorna wilda','opis musi byc','super pokoj dla studenta', 2002,100);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(101,'2021-11-15','poznan','polska','PLN','wilda','12/3',10,'61-78',999,'POKOJ','2021-11-18','wlkp','gorna wilda','opis musi byc','super pokoj dla studenta wersja 2', 2002,101);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(102,'2021-11-15','poznan','polska','PLN','wilda','12/3',10,'61-78',999,'POKOJ','2021-11-18','wlkp','gorna wilda','opis musi byc','super pokoj dla studenta wersja 3', 2002,102);

insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(103,'2021-11-15','warszawa','polska','EUR','lazarz','12',10,'61-783',111,'MIESZKANIE','2021-10-25','malopl','dolna wilda','ciasny ale wlasny','super pokoj dla studenta wersja 3', 1999,103);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(104,'1999-01-01','paryz','francja','CHF','gorczyn','12/113',13,'61-782',222,'DOM','2021-11-18','wlkp','gorna wilda','giga chata','super pokoj dla nikogo', 2005,104);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(105,'2000-12-31','wroclaw','polska','DOL','wilda','122/3',13,'61-783',111,'POKOJ','2021-10-25','wlkp','dolna wilda','opis musi byc','pokoj dla studenta', 1999,105);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(106,'2001-02-28','gdansk','polska','YEN','wilda','112/13',10,'61-782',222,'MIESZKANIE','2021-11-18','wlkp','gorna wilda','giga chata','super', 2002,106);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(107,'2020-05-12','czechowice','polska','FNT','lazarz','212/23',22,'61-783',1212,'POKOJ','2021-11-18','malopl','dolna wilda','chata chada','super pokoj', 2005,107);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(108,'2021-10-25','berlin','niemcy','FRN','wilda','133',33,'61-782',1212,'POKOJ','2021-11-18','zachpom','gorna wilda','domek romek','super pokoj', 1999,108);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(109,'2021-12-05','nowe miasto','czechy','JPG','gorczyn','112a/3',33,'61783',1212,'POKOJ','1999-01-01','wlkp','gorczyn','w domu najlepiej','czadowy pokoj dla nas', 2002,109);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(110,'2021-03-10','gdansk','polska','OMG','wilda','12/3a',10,'61228',222,'MIESZKANIE','2021-11-18','malopl','gorna wilda','tu tez milo jest','super wersja 3', 2002,110);
insert into announcement(id, available_from, city, country, currency, district, house_number, living_space, postal_code, price, property_type, publication_date, state, street, text, title, year_built, web_user_id) values(111,'2021-07-12','lodz','czechy','ABC','rataje','122a/3',33,'6178',444,'DOM','1999-01-01','zachpom','gorczyn','super domor','wersja 3', 2005,111);

insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (100, true, true, true, true, false, false, false, true, true, false, true, false, true, 50, false, true, true, false, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (101, true, true, true, true, true, true, true, true, true, true, true, true, true, 999, true, true, true, true, true, true, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (102, false, false, false, false, false, false, false, false, false, false, false, false, false, 0, false, false, false, false, false, false, false);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (103, true, false, true, true, false, false, false, false, true, false, true, false, true, -3, false, true, false, true, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (104, false, true, true, true, false, false, true, true, true, false, true, false, true, 555, false, true, true, false, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (105, false, true, true, true, true, false, false, true, true, true, true, false, true, 20, false, true, true, false, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (106, true, true, true, true, false, false, false, true, true, false, true, false, true, 40, false, true, true, false, false, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (107, true, true, true, true, false, false, false, true, true, false, true, false, true, 200, false, false, true, false, true, false, false);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (108, false, true, false, true, false, false, false, true, false, false, true, false, true, 50, false, true, true, true, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (109, true, true, true, true, false, false, false, true, true, false, true, false, true, 0, false, true, true, false, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (110, true, true, true, true, false, false, false, true, true, true, true, false, false, 150, false, true, true, false, true, false, true);
insert into announcement_details(id, bath, shower, microwave, oven, petsAllowed, elevator, nearPark, fenced, nearTram, nearBus, wifi, ethernetOutlets, internet, internetSpeed, tv, dishwasher, clothersDryer, nearShoppingMall, nearBakery, nearFoodMarket, nearSupermarket) values (111, true, false, true, true, true, false, true, true, true, false, true, false, true, 50, false, true, true, false, true, false, false);